apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  externalIPs:
          - 172.31.42.239
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
